# Generated by Django 4.2.6 on 2023-10-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookno', models.CharField(db_column='bookNo', max_length=10, primary_key=True, serialize=False)),
                ('bookname', models.CharField(db_column='bookName', max_length=30)),
                ('bookauthor', models.CharField(db_column='bookAuthor', max_length=20)),
                ('bookprice', models.IntegerField(blank=True, db_column='bookPrice', null=True)),
                ('bookdate', models.DateField(blank=True, db_column='bookDate', null=True)),
                ('bookstock', models.IntegerField(blank=True, db_column='bookStock', null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pubno', models.CharField(db_column='pubNo', max_length=10, primary_key=True, serialize=False)),
                ('pubname', models.CharField(db_column='pubName', max_length=20)),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
    ]
