# Generated by Django 4.2.6 on 2023-10-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prd_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prd_name', models.CharField(blank=True, max_length=20, null=True)),
                ('prd_price', models.IntegerField(blank=True, null=True)),
                ('prd_maker', models.CharField(blank=True, max_length=30, null=True)),
                ('prd_color', models.CharField(blank=True, max_length=10, null=True)),
                ('ctg_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
